FROM  openjdk:15
RUN mkdir -p /app/
ADD /build/libs/sooner.jar /app/sooner.jar
RUN mkdir -p /tokens/
ADD /tokens/StoredCredential /tokens/StoredCredential
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/sooner.jar"]